#!/bin/bash

### BEGIN INIT INFO
# Provides:          mediacenter-encoder
# Required-Start:    $local_fs $remote_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Transcode movies in the background.
# Description: Background worker for transcoding downloaded movies.
### END INIT INFO

APPLICATION_ROOT=/var/www/mediacenter/
PID_FILE=$APPLICATION_ROOT/mediacenter-encoder.pid

function stop_job {
    echo "Stopping mediacenter-encoder"
    PID=$([ -f $PID_FILE ] && cat $PID_FILE)
    [ $PID ] && kill -9 $PID
    rm $PID_FILE
    echo "Stopped"
}

function start_job {
    if [ -f $PID_FILE ]
    then
        stop_job
    fi
    echo "Starting mediacenter-encoder"
    pushd $APPLICATION_ROOT
    nohup ruby encoder.rb &
    PID=$!
    echo $PID > $PID_FILE
    popd
    echo "Started"
}

# Carry out specific functions when asked to by the system
case "$1" in
    start)
        start_job
        ;;
    stop)
        stop_job
        ;;
    *)
        echo "Usage: /etc/init.d/$0 {start|stop}"
        exit 1
        ;;
esac

exit 0
